version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-typescript-lambda"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"hello-world-typescript-lambda\""
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o931l0m2ej6a"
s3_prefix = "hello-world-typesript-lambda"
